# Generated by Django 5.1.7 on 2025-03-19 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipperliga', '0002_achievementtype_leaguereport_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('show_full_name', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('facebook_link', models.URLField(blank=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('preferred_sport', models.CharField(blank=True, max_length=100)),
                ('total_bets', models.IntegerField(default=0)),
                ('total_correct_bets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_leagues', models.ManyToManyField(blank=True, to='tipperliga.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_theme', models.CharField(choices=[('light', 'Svetlá'), ('dark', 'Tmavá'), ('system', 'Systémová')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('sk', 'Slovenčina'), ('en', 'Angličtina'), ('cz', 'Čeština')], default='sk', max_length=5)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Okamžité'), ('daily', 'Denne'), ('weekly', 'Týždenne')], default='daily', max_length=20)),
                ('profile_visibility', models.CharField(choices=[('public', 'Verejný'), ('friends', 'Len priatelia'), ('private', 'Súkromný')], default='public', max_length=20)),
                ('show_betting_history', models.BooleanField(default=True)),
                ('allow_friend_requests', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
