# Generated by Django 5.1.7 on 2025-03-19 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipperliga', '0004_socialinteractionlog_friendrequest_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_prediction_home', models.IntegerField()),
                ('challenger_prediction_away', models.IntegerField()),
                ('challenged_user_prediction_home', models.IntegerField(blank=True, null=True)),
                ('challenged_user_prediction_away', models.IntegerField(blank=True, null=True)),
                ('stake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Čaká na schválenie'), ('accepted', 'Prijatá'), ('rejected', 'Zamietnutá'), ('completed', 'Ukončená')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to=settings.AUTH_USER_MODEL)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipperliga.match')),
            ],
        ),
    ]
