# Generated by Django 5.1.7 on 2025-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipperliga', '0011_reporttype_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
