# Generated by Django 5.1.7 on 2025-03-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipperliga', '0012_competitioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerposition',
            name='sport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='tipperliga.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipperliga.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='tipperliga.team')),
            ],
        ),
    ]
