# Generated by Django 5.1.7 on 2025-03-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipperliga', '0013_playerposition_sport_playertransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBettingHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_prediction', models.IntegerField()),
                ('away_score_prediction', models.IntegerField()),
                ('actual_home_score', models.IntegerField()),
                ('actual_away_score', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('match_date', models.DateTimeField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipperliga.bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipperliga.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_date'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
